### ISSUE TITLE
enhancement - consider cherry picking upstream open webui docker compose 

### ISSUE THREAD

**Issue by johndpope** [travisvn/openai-edge-tts#3]
background
(I never used open webui before)

when i read the readme - i got confused because this repo doesn't have a gui, right?

Open WebUI

and then this is not the openai console - though i had to look around - 

either update the readme to say - hey bozo - you need the openui repo running too  - and then go to localhost:3000 and go webui etc

https://github.com/open-webui/open-webui/blob/main/docker-compose.yaml

```
version: '3.8'
services:
  app:
    build: .
    ports:
      - '${PORT:-5050}:5050'
    env_file:
      - .env
    environment: # optionally define in -e argument when running docker command
      - API_KEY=${API_KEY}
      - PORT=${PORT}
      - DEFAULT_VOICE=${DEFAULT_VOICE}
      - DEFAULT_RESPONSE_FORMAT=${DEFAULT_RESPONSE}
      - DEFAULT_SPEED=${DEFAULT_SPEED}
      - DEFAULT_LANGUAGE=${DEFAULT_LANGUAGE}
      - REQUIRE_API_KEY=${REQUIRE_API_KEY}
    volumes:
      - .:/app

  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}
```
